### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertText' of undefined

### ISSUE THREAD

**Issue by thadswan** [maxkoryukov/atom-password-generator#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-password-generator](https://github.com/maxkoryukov/atom-password-generator) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'insertText' of undefined

```
At C:\Users\thad.swan\.atom\packages\atom-password-generator\lib\password-generator.js:103

TypeError: Cannot read property 'insertText' of undefined
    at Object._gen (/packages/atom-password-generator/lib/password-generator.js:103:16)
    at Object.medium (/packages/atom-password-generator/lib/password-generator.js:113:15)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.22.1/resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.22.1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:49.9.0 core:confirm (input.hidden-input)
     -0:09.9.0 password-generator:medium (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-password-generator 0.3.0 
```

**Comment by maxkoryukov** [comment]
thank you for the detailed report, I will fix soon
